#!/bin/bash

# Copied mostly from https://gist.github.com/rumpelsepp/d646750910be19332753
# TODO Write in python

# Check if pacaur is already installed
if type pacaur > /dev/null 2>&1; then
  exit
fi

START=$(pwd)
BUILDROOT="$(mktemp -d)"

# Make sure we can even build packages on arch linux.
sudo pacman -S --needed --noconfirm base-devel git

mkdir -p "$BUILDROOT"
cd "$BUILDROOT" || exit 1

cd $BUILDROOT || exit 1
git clone "https://aur.archlinux.org/pacaur.git"

cd "$BUILDROOT/pacaur" || exit 1
makepkg --syncdeps --install --noconfirm

cd "$START" || exit 1
rm -rf "$BUILDROOT"

if ! type pacaur > /dev/null 2>&1; then
  echo "pacaur installation failed"
  exit 1
fi
